"""Generate deterministic SQL to load the validated NER GeoJSON into PostGIS."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = ROOT / "data" / "geodata" / "ner"
OUTPUT_PATH = ROOT / "backend" / "db" / "seeds" / "ner_hierarchy.sql"


def load_features(filename: str) -> list[dict[str, Any]]:
    path = SOURCE_DIR / filename
    with path.open(encoding="utf-8") as handle:
        document = json.load(handle)
    if document.get("type") != "FeatureCollection":
        raise ValueError(f"{path} is not a FeatureCollection")
    return document["features"]


def sql_text(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def geometry_sql(feature: dict[str, Any]) -> str:
    geometry = feature.get("geometry")
    if not geometry:
        raise ValueError("Cannot seed a feature with null geometry")
    return f"ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON({sql_text(json.dumps(geometry, separators=(',', ':')))}), 4326))"


def main() -> None:
    states = load_features("states.geojson")
    districts = load_features("districts.geojson")
    regions = load_features("ner_boundary.geojson")
    if len(regions) != 1 or regions[0]["properties"].get("region_id") != "NER":
        raise ValueError("Expected exactly one NER region feature")
    if len(states) != 8 or len(districts) != 119:
        raise ValueError("Expected 8 states and 119 districts")

    lines = [
        "-- Generated by backend/scripts/generate_ner_postgis_seed.py",
        "BEGIN;",
        "INSERT INTO terrasense.regions "
        "(region_id, region_name, source, source_version, geometry) VALUES",
    ]
    region = regions[0]["properties"]
    lines.append(
        "("
        + ", ".join(
            [
                sql_text(region["region_id"]),
                sql_text(region["region_name"]),
                sql_text(region["source"]),
                sql_text(region["source_version"]),
                geometry_sql(regions[0]),
            ]
        )
        + ") ON CONFLICT (region_id) DO UPDATE SET "
        "region_name = EXCLUDED.region_name, geometry = EXCLUDED.geometry;"
    )

    lines.append(
        "INSERT INTO terrasense.states "
        "(state_id, state_name, region_id, source_feature_id, source, source_version, geometry) VALUES"
    )
    state_values = []
    for feature in states:
        p = feature["properties"]
        state_values.append(
            "("
            + ", ".join(
                [
                    sql_text(p["state_id"]),
                    sql_text(p["state_name"]),
                    sql_text(p["region_id"]),
                    sql_text(p["source_feature_id"]),
                    sql_text(p["source"]),
                    sql_text(p["source_version"]),
                    geometry_sql(feature),
                ]
            )
            + ")"
        )
    lines.append(
        ",\n".join(state_values)
        + " ON CONFLICT (state_id) DO UPDATE SET "
        "state_name = EXCLUDED.state_name, region_id = EXCLUDED.region_id, "
        "geometry = EXCLUDED.geometry;"
    )

    lines.append(
        "INSERT INTO terrasense.districts "
        "(district_id, district_name, state_id, lgd_code, source_feature_id, source, source_version, geometry) VALUES"
    )
    district_values = []
    for feature in districts:
        p = feature["properties"]
        district_values.append(
            "("
            + ", ".join(
                [
                    sql_text(p["district_id"]),
                    sql_text(p["district_name"]),
                    sql_text(p["state_id"]),
                    sql_text(p.get("lgd_code")),
                    sql_text(p["source_feature_id"]),
                    sql_text(p["source"]),
                    sql_text(p["source_version"]),
                    geometry_sql(feature),
                ]
            )
            + ")"
        )
    lines.append(
        ",\n".join(district_values)
        + " ON CONFLICT (district_id) DO UPDATE SET "
        "district_name = EXCLUDED.district_name, state_id = EXCLUDED.state_id, "
        "lgd_code = EXCLUDED.lgd_code, geometry = EXCLUDED.geometry;"
    )
    lines.extend(["COMMIT;", ""])
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH} ({len(states)} states, {len(districts)} districts)")


if __name__ == "__main__":
    main()
